version: '3.9'

services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: moonelpy/ndse:counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
       - 80:3001
    depends_on: 
      - storage
  library: 
    image: moonelpy/ndse:library_with_counter
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
    ports:
      - 81:3000
    depends_on: 
      - storage
      - counter