version: '3.9'

services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: moonelpy/ndse:counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
       - 80:3001
    depends_on: 
      - storage
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: bind
        source: ./data/mongodb
        target: /data/db  
  library: 
    image: moonelpy/ndse:library_with_mongo
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
      - MONGO_URL=mongodb://root:password@mongo:27017/
    ports:
      - 81:3000
    depends_on: 
      - storage
      - counter
      - mongo